### ISSUE TITLE
Nástroj na testování se zacyklí na testu 07_strings 10

### ISSUE THREAD

**Issue by oberreiterm** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#30]
Pythoní interpret se zacyklí na, referenční n - konkrétní kód poslán soukromě.
Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/ifjcode17-tests", line 9, in <module>
    load_entry_point('IFJcode17-toolkit==1.1.8', 'console_scripts', 'ifjcode17-tests')()
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/test/main.py", line 42, in main
    return runner.run()
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/test/runner.py", line 131, in run
    self._run_test(test_info)
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/test/runner.py", line 234, in _run_test
    state = self._interpret_price(report.compiler_stdout, test_info)
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/test/runner.py", line 273, in _interpret_price
    return interpreter.run()
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/interpreter/interpreter.py", line 62, in run    instruction.run(state)
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/interpreter/instruction.py", line 193, in run
    command(state, *self.operands)  # fake instance argument
  File "/usr/local/lib/python3.5/dist-packages/IFJcode17_toolkit-1.1.8-py3.5.egg/ifj2017/interpreter/instruction.py", line 93, in operands
    return filter(None, (self.op0, self.op1, self.op2,))
KeyboardInterrupt
```

**Comment by thejoeejoee** [comment]
Opraveno, s dalším releasem si vyzkoušej, @oberreiterm, jestliže bude OK, zavři prosím.

**Comment by thejoeejoee** [comment]
`1.2` je venku, vyzkoušej prosím
