### ISSUE TITLE
Verze 1.3.8 nenastartuje

### ISSUE THREAD

**Issue by Trsak** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#48]
Při instalaci přes pip testy nefungují:

```
Traceback (most recent call last):  
  File "/usr/local/bin/ifjcode17-tests", line 7, in <module>  
    from ifj2017.test.main import main  
  File "/usr/local/lib/python3.5/dist-packages/ifj2017/test/main.py", line 9, in <module>  
    import argcomplete  
ImportError: No module named 'argcomplete'
```

Manuální instalace funguje, takže to chápu tak, že poslední vydaná verze obsahuje chybu

**Comment by thejoeejoee** [comment]
Opraveno v `1.3.9`, díky za report. Jestli OK, zavři prosím.
